version: "3"

services:
  db:
    container_name: mysql_db
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pj5data
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  python_scripts:
    container_name: python_scripts
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - db_created:/db_created
    depends_on:
      - db

  backend:
    container_name: api
    build:
      context: ./app
      dockerfile: Dockerfile.app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code
    depends_on:
      - db

volumes:
  mysqldata:
  db_created:
