version: '3'

services:
  db:
    container_name: mysql_db
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pj5data
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  mysqldata: