# Generated by Django 4.2.2 on 2023-06-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_arquivoxml_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandeareaconhecimento',
            name='nome_formatado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
