# Generated by Django 4.2.2 on 2023-06-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grandeareaconhecimento_nome_formatado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='areas_conhecimento',
            field=models.ManyToManyField(related_name='artigos', through='core.ArtigoAreaConhecimento', to='core.grandeareaconhecimento'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='areas_conhecimento',
            field=models.ManyToManyField(related_name='autores', through='core.AutorAreaConhecimento', to='core.grandeareaconhecimento'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='artigos',
            field=models.ManyToManyField(related_name='autores', through='core.AutorArtigo', to='core.artigo'),
        ),
    ]
