# Generated by Django 4.2.2 on 2023-06-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_artigo_areas_conhecimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orientacao',
            name='orientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orientacoes', to='core.autor'),
        ),
    ]
